name: Destroy TF State Infrastructure - ID: ${{ github.run_id }}

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: 'Type YES to confirm destroy action'
        required: false
        default: ''

jobs:
  plan:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ fromJSON(secrets.AZURE_CREDENTIALS).clientId }}
      ARM_CLIENT_SECRET: ${{ fromJSON(secrets.AZURE_CREDENTIALS).clientSecret }}
      ARM_SUBSCRIPTION_ID: ${{ fromJSON(secrets.AZURE_CREDENTIALS).subscriptionId }}
      ARM_TENANT_ID: ${{ fromJSON(secrets.AZURE_CREDENTIALS).tenantId }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7
      - name: Clean .terraform directory
        working-directory: backend-bootstrap
        run: rm -rf .terraform
      - name: Print working directory
        run: pwd
        working-directory: backend-bootstrap
      - name: List files
        run: ls -l
        working-directory: backend-bootstrap
      - name: Check if storage account exists
        id: check-storage
        run: |
          if az storage account show --name "${{ secrets.BACKEND_STORAGE_ACCOUNT || 'akstfstate01' }}" --resource-group "${{ secrets.BACKEND_RESOURCE_GROUP || 'jit-se-testing-aks-tfstate-rg01' }}" >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
      - name: Check if remote state has resources
        id: check-remote-state
        if: steps.check-storage.outputs.exists == 'true'
        run: |
          echo "Checking if remote state contains resources..."
          # Try to get state from remote backend
          terraform init -upgrade \
            -backend-config="resource_group_name=${{ secrets.BACKEND_RESOURCE_GROUP || 'jit-se-testing-aks-tfstate-rg01' }}" \
            -backend-config="storage_account_name=${{ secrets.BACKEND_STORAGE_ACCOUNT || 'akstfstate01' }}" \
            -backend-config="container_name=${{ secrets.BACKEND_CONTAINER || 'tfstate' }}" \
            -backend-config="key=backend-bootstrap.tfstate" >/dev/null 2>&1
          
          if terraform state list 2>/dev/null | grep -q .; then
            echo "has_resources=true" >> $GITHUB_OUTPUT
            echo "Remote state contains resources"
          else
            echo "has_resources=false" >> $GITHUB_OUTPUT
            echo "Remote state is empty"
          fi
      - name: Debug - Show storage account check result
        run: |
          echo "Storage account exists: ${{ steps.check-storage.outputs.exists }}"
          echo "Remote state has resources: ${{ steps.check-remote-state.outputs.has_resources }}"
      - name: Terraform Init (Local State)
        if: steps.check-storage.outputs.exists == 'false' || (steps.check-storage.outputs.exists == 'true' && steps.check-remote-state.outputs.has_resources == 'false')
        working-directory: backend-bootstrap
        timeout-minutes: 10
        run: |
          echo "Starting terraform init with local state (first run or empty remote state)..."
          # Remove backend block for first run
          sed -i '/backend "azurerm" {/,/}/d' main.tf
          terraform init -upgrade -input=false
          echo "Terraform init completed successfully"
      - name: Terraform Init (Remote State)
        if: steps.check-storage.outputs.exists == 'true' && steps.check-remote-state.outputs.has_resources == 'true'
        working-directory: backend-bootstrap
        timeout-minutes: 10
        run: |
          echo "Starting terraform init with remote state..."
          terraform init -upgrade \
            -backend-config="resource_group_name=${{ secrets.BACKEND_RESOURCE_GROUP || 'jit-se-testing-aks-tfstate-rg01' }}" \
            -backend-config="storage_account_name=${{ secrets.BACKEND_STORAGE_ACCOUNT || 'akstfstate01' }}" \
            -backend-config="container_name=${{ secrets.BACKEND_CONTAINER || 'tfstate' }}" \
            -backend-config="key=backend-bootstrap.tfstate"
          echo "Terraform init with remote state completed successfully"
      - name: Select workspace
        working-directory: backend-bootstrap
        run: terraform workspace select default || terraform workspace new default
      - name: Debug - Show current workspace
        working-directory: backend-bootstrap
        run: terraform workspace show
      - name: Debug - List state resources
        working-directory: backend-bootstrap
        run: |
          if terraform state list 2>/dev/null; then
            echo "State file exists and contains resources"
          else
            echo "No state file found or state file is empty (this is normal for first run)"
          fi
      - name: Debug - Show backend config
        working-directory: backend-bootstrap
        run: |
          if terraform show -json 2>/dev/null | jq '.values.root_module.resources[].address' 2>/dev/null; then
            echo "Resources found in state"
          else
            echo "No resources in state (this is normal for first run)"
          fi
      - name: Terraform Plan
        working-directory: backend-bootstrap
        run: terraform plan -destroy
  destroy:
    needs: plan
    runs-on: ubuntu-latest
    environment:
      name: manual-approval
    env:
      ARM_CLIENT_ID: ${{ fromJSON(secrets.AZURE_CREDENTIALS).clientId }}
      ARM_CLIENT_SECRET: ${{ fromJSON(secrets.AZURE_CREDENTIALS).clientSecret }}
      ARM_SUBSCRIPTION_ID: ${{ fromJSON(secrets.AZURE_CREDENTIALS).subscriptionId }}
      ARM_TENANT_ID: ${{ fromJSON(secrets.AZURE_CREDENTIALS).tenantId }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7
      - name: Check if storage account exists
        id: check-storage
        run: |
          if az storage account show --name "${{ secrets.BACKEND_STORAGE_ACCOUNT || 'akstfstate01' }}" --resource-group "${{ secrets.BACKEND_RESOURCE_GROUP || 'jit-se-testing-aks-tfstate-rg01' }}" >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
      - name: Check if remote state has resources
        id: check-remote-state
        if: steps.check-storage.outputs.exists == 'true'
        run: |
          echo "Checking if remote state contains resources..."
          # Try to get state from remote backend
          terraform init -upgrade \
            -backend-config="resource_group_name=${{ secrets.BACKEND_RESOURCE_GROUP || 'jit-se-testing-aks-tfstate-rg01' }}" \
            -backend-config="storage_account_name=${{ secrets.BACKEND_STORAGE_ACCOUNT || 'akstfstate01' }}" \
            -backend-config="container_name=${{ secrets.BACKEND_CONTAINER || 'tfstate' }}" \
            -backend-config="key=backend-bootstrap.tfstate" >/dev/null 2>&1
          
          if terraform state list 2>/dev/null | grep -q .; then
            echo "has_resources=true" >> $GITHUB_OUTPUT
            echo "Remote state contains resources"
          else
            echo "has_resources=false" >> $GITHUB_OUTPUT
            echo "Remote state is empty"
          fi
      - name: Debug - Show storage account check result
        run: |
          echo "Storage account exists: ${{ steps.check-storage.outputs.exists }}"
          echo "Remote state has resources: ${{ steps.check-remote-state.outputs.has_resources }}"
      - name: Terraform Init (Local State)
        if: steps.check-storage.outputs.exists == 'false' || (steps.check-storage.outputs.exists == 'true' && steps.check-remote-state.outputs.has_resources == 'false')
        working-directory: backend-bootstrap
        timeout-minutes: 10
        run: |
          echo "Starting terraform init with local state (first run or empty remote state)..."
          # Remove backend block for first run
          sed -i '/backend "azurerm" {/,/}/d' main.tf
          terraform init -upgrade -input=false
          echo "Terraform init completed successfully"
      - name: Terraform Init (Remote State)
        if: steps.check-storage.outputs.exists == 'true' && steps.check-remote-state.outputs.has_resources == 'true'
        working-directory: backend-bootstrap
        timeout-minutes: 10
        run: |
          echo "Starting terraform init with remote state..."
          terraform init -upgrade \
            -backend-config="resource_group_name=${{ secrets.BACKEND_RESOURCE_GROUP || 'jit-se-testing-aks-tfstate-rg01' }}" \
            -backend-config="storage_account_name=${{ secrets.BACKEND_STORAGE_ACCOUNT || 'akstfstate01' }}" \
            -backend-config="container_name=${{ secrets.BACKEND_CONTAINER || 'tfstate' }}" \
            -backend-config="key=backend-bootstrap.tfstate"
          echo "Terraform init with remote state completed successfully"
      - name: Import existing resources to state (if they exist)
        if: steps.check-storage.outputs.exists == 'true'
        working-directory: backend-bootstrap
        run: |
          echo "Importing existing Azure resources to Terraform state..."
          
          # Get resource group ID
          RG_NAME="${{ secrets.BACKEND_RESOURCE_GROUP || 'jit-se-testing-aks-tfstate-rg01' }}"
          RG_ID=$(az group show --name "$RG_NAME" --query id -o tsv 2>/dev/null || echo "")
          
          if [ -n "$RG_ID" ]; then
            echo "Importing resource group: $RG_NAME"
            terraform import azurerm_resource_group.tfstate "$RG_ID" || echo "Resource group already in state or import failed"
          fi
          
          # Get storage account ID
          SA_NAME="${{ secrets.BACKEND_STORAGE_ACCOUNT || 'akstfstate01' }}"
          SA_ID=$(az storage account show --name "$SA_NAME" --resource-group "$RG_NAME" --query id -o tsv 2>/dev/null || echo "")
          
          if [ -n "$SA_ID" ]; then
            echo "Importing storage account: $SA_NAME"
            terraform import azurerm_storage_account.tfstate "$SA_ID" || echo "Storage account already in state or import failed"
          fi
          
          # Get storage container ID
          CONTAINER_NAME="${{ secrets.BACKEND_CONTAINER || 'tfstate' }}"
          CONTAINER_ID="$SA_NAME/$CONTAINER_NAME"
          
          if [ -n "$SA_ID" ]; then
            echo "Importing storage container: $CONTAINER_NAME"
            terraform import azurerm_storage_container.tfstate "$CONTAINER_ID" || echo "Storage container already in state or import failed"
          fi
          
          echo "Import completed"
      - name: Select workspace
        working-directory: backend-bootstrap
        run: terraform workspace select default || terraform workspace new default
      - name: Import existing resources to state (if they exist)
        if: steps.check-storage.outputs.exists == 'true'
        working-directory: backend-bootstrap
        run: |
          echo "Importing existing Azure resources to Terraform state..."
          
          # Get resource group ID
          RG_NAME="${{ secrets.BACKEND_RESOURCE_GROUP || 'jit-se-testing-aks-tfstate-rg01' }}"
          RG_ID=$(az group show --name "$RG_NAME" --query id -o tsv 2>/dev/null || echo "")
          
          if [ -n "$RG_ID" ]; then
            echo "Importing resource group: $RG_NAME"
            terraform import azurerm_resource_group.tfstate "$RG_ID" || echo "Resource group already in state or import failed"
          fi
          
          # Get storage account ID
          SA_NAME="${{ secrets.BACKEND_STORAGE_ACCOUNT || 'akstfstate01' }}"
          SA_ID=$(az storage account show --name "$SA_NAME" --resource-group "$RG_NAME" --query id -o tsv 2>/dev/null || echo "")
          
          if [ -n "$SA_ID" ]; then
            echo "Importing storage account: $SA_NAME"
            terraform import azurerm_storage_account.tfstate "$SA_ID" || echo "Storage account already in state or import failed"
          fi
          
          # Get storage container ID
          CONTAINER_NAME="${{ secrets.BACKEND_CONTAINER || 'tfstate' }}"
          CONTAINER_ID="$SA_NAME/$CONTAINER_NAME"
          
          if [ -n "$SA_ID" ]; then
            echo "Importing storage container: $CONTAINER_NAME"
            terraform import azurerm_storage_container.tfstate "$CONTAINER_ID" || echo "Storage container already in state or import failed"
          fi
          
          echo "Import completed"
      - name: Terraform Destroy
        if: github.event.inputs.confirm_destroy == 'YES'
        working-directory: backend-bootstrap
        run: |
          echo 'WARNING: You are about to destroy backend resources!'
          terraform destroy -auto-approve
      - name: Destroy Not Confirmed
        if: github.event.inputs.confirm_destroy != 'YES'
        run: |
          echo 'Destroy action was requested, but confirmation was not provided. Skipping destroy.'
          exit 1 