name: Destroy TF State

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: 'Type YES to confirm destroy action'
        required: false
        default: ''

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7
      - name: Clean .terraform directory
        working-directory: backend-bootstrap
        run: rm -rf .terraform
      - name: Print working directory
        run: pwd
        working-directory: backend-bootstrap
      - name: List files
        run: ls -l
        working-directory: backend-bootstrap
      - name: Check if storage account exists
        id: check-storage
        run: |
          if az storage account show --name "${{ secrets.BACKEND_STORAGE_ACCOUNT || 'akstfstate01' }}" --resource-group "${{ secrets.BACKEND_RESOURCE_GROUP || 'jit-se-testing-aks-tfstate-rg01' }}" >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
      - name: Debug - Show storage account check result
        run: |
          echo "Storage account exists: ${{ steps.check-storage.outputs.exists }}"
      - name: Terraform Init (Local State)
        if: steps.check-storage.outputs.exists == 'false'
        working-directory: backend-bootstrap
        run: terraform init -upgrade
      - name: Terraform Init (Remote State)
        if: steps.check-storage.outputs.exists == 'true'
        working-directory: backend-bootstrap
        run: |
          terraform init -upgrade \
            -backend-config="resource_group_name=${{ secrets.BACKEND_RESOURCE_GROUP || 'jit-se-testing-aks-tfstate-rg01' }}" \
            -backend-config="storage_account_name=${{ secrets.BACKEND_STORAGE_ACCOUNT || 'akstfstate01' }}" \
            -backend-config="container_name=${{ secrets.BACKEND_CONTAINER || 'tfstate' }}" \
            -backend-config="key=backend-bootstrap.tfstate"
      - name: Select workspace
        working-directory: backend-bootstrap
        run: terraform workspace select default || terraform workspace new default
      - name: Debug - Show current workspace
        working-directory: backend-bootstrap
        run: terraform workspace show
      - name: Debug - List state resources
        working-directory: backend-bootstrap
        run: terraform state list
      - name: Debug - Show backend config
        working-directory: backend-bootstrap
        run: terraform show -json | jq '.values.root_module.resources[].address' 2>/dev/null || echo "No resources in state"
      - name: Terraform Plan
        working-directory: backend-bootstrap
        run: terraform plan -destroy
  destroy:
    needs: plan
    runs-on: ubuntu-latest
    environment:
      name: manual-approval
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7
      - name: Check if storage account exists
        id: check-storage
        run: |
          if az storage account show --name "${{ secrets.BACKEND_STORAGE_ACCOUNT || 'akstfstate01' }}" --resource-group "${{ secrets.BACKEND_RESOURCE_GROUP || 'jit-se-testing-aks-tfstate-rg01' }}" >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
      - name: Debug - Show storage account check result
        run: |
          echo "Storage account exists: ${{ steps.check-storage.outputs.exists }}"
      - name: Terraform Init (Local State)
        if: steps.check-storage.outputs.exists == 'false'
        working-directory: backend-bootstrap
        run: terraform init -upgrade
      - name: Terraform Init (Remote State)
        if: steps.check-storage.outputs.exists == 'true'
        working-directory: backend-bootstrap
        run: |
          terraform init -upgrade \
            -backend-config="resource_group_name=${{ secrets.BACKEND_RESOURCE_GROUP || 'jit-se-testing-aks-tfstate-rg01' }}" \
            -backend-config="storage_account_name=${{ secrets.BACKEND_STORAGE_ACCOUNT || 'akstfstate01' }}" \
            -backend-config="container_name=${{ secrets.BACKEND_CONTAINER || 'tfstate' }}" \
            -backend-config="key=backend-bootstrap.tfstate"
      - name: Select workspace
        working-directory: backend-bootstrap
        run: terraform workspace select default || terraform workspace new default
      - name: Terraform Destroy
        if: github.event.inputs.confirm_destroy == 'YES'
        working-directory: backend-bootstrap
        run: |
          echo 'WARNING: You are about to destroy backend resources!'
          terraform destroy -auto-approve
      - name: Destroy Not Confirmed
        if: github.event.inputs.confirm_destroy != 'YES'
        run: |
          echo 'Destroy action was requested, but confirmation was not provided. Skipping destroy.'
          exit 1 